<?php

namespace IronWeb\ArticlesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleUserRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleUserRatingRepository extends EntityRepository
{
}
